// Code generated by MockGen. DO NOT EDIT.
// Source: ./addentryview.go
//
// Generated by this command:
//
//	mockgen -destination=../mocks/ui/mock_addentryview.go -source=./addentryview.go
//

// Package mock_ui is a generated GoMock package.
package mock_ui

import (
	secretsdb "keepassui/internal/secretsdb"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEntryUpdater is a mock of EntryUpdater interface.
type MockEntryUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockEntryUpdaterMockRecorder
}

// MockEntryUpdaterMockRecorder is the mock recorder for MockEntryUpdater.
type MockEntryUpdaterMockRecorder struct {
	mock *MockEntryUpdater
}

// NewMockEntryUpdater creates a new mock instance.
func NewMockEntryUpdater(ctrl *gomock.Controller) *MockEntryUpdater {
	mock := &MockEntryUpdater{ctrl: ctrl}
	mock.recorder = &MockEntryUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryUpdater) EXPECT() *MockEntryUpdaterMockRecorder {
	return m.recorder
}

// AddEntry mocks base method.
func (m *MockEntryUpdater) AddEntry(templateEntry *secretsdb.SecretEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddEntry", templateEntry)
}

// AddEntry indicates an expected call of AddEntry.
func (mr *MockEntryUpdaterMockRecorder) AddEntry(templateEntry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEntry", reflect.TypeOf((*MockEntryUpdater)(nil).AddEntry), templateEntry)
}

// ModifyEntry mocks base method.
func (m *MockEntryUpdater) ModifyEntry(templateEntry *secretsdb.SecretEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ModifyEntry", templateEntry)
}

// ModifyEntry indicates an expected call of ModifyEntry.
func (mr *MockEntryUpdaterMockRecorder) ModifyEntry(templateEntry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyEntry", reflect.TypeOf((*MockEntryUpdater)(nil).ModifyEntry), templateEntry)
}
