// Code generated by MockGen. DO NOT EDIT.
// Source: ./secretsreader.go
//
// Generated by this command:
//
//	mockgen -destination=../mocks/secretsreader/mock_secretsreader.go -source=./secretsreader.go
//

// Package mock_secretsreader is a generated GoMock package.
package mock_secretsreader

import (
	secretsdb "keepassui/internal/secretsdb"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSecretReader is a mock of SecretReader interface.
type MockSecretReader struct {
	ctrl     *gomock.Controller
	recorder *MockSecretReaderMockRecorder
}

// MockSecretReaderMockRecorder is the mock recorder for MockSecretReader.
type MockSecretReaderMockRecorder struct {
	mock *MockSecretReader
}

// NewMockSecretReader creates a new mock instance.
func NewMockSecretReader(ctrl *gomock.Controller) *MockSecretReader {
	mock := &MockSecretReader{ctrl: ctrl}
	mock.recorder = &MockSecretReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretReader) EXPECT() *MockSecretReaderMockRecorder {
	return m.recorder
}

// GetContentInBytes mocks base method.
func (m *MockSecretReader) GetContentInBytes() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContentInBytes")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetContentInBytes indicates an expected call of GetContentInBytes.
func (mr *MockSecretReaderMockRecorder) GetContentInBytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContentInBytes", reflect.TypeOf((*MockSecretReader)(nil).GetContentInBytes))
}

// GetPassword mocks base method.
func (m *MockSecretReader) GetPassword() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassword")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPassword indicates an expected call of GetPassword.
func (mr *MockSecretReaderMockRecorder) GetPassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassword", reflect.TypeOf((*MockSecretReader)(nil).GetPassword))
}

// GetUriID mocks base method.
func (m *MockSecretReader) GetUriID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUriID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUriID indicates an expected call of GetUriID.
func (mr *MockSecretReaderMockRecorder) GetUriID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUriID", reflect.TypeOf((*MockSecretReader)(nil).GetUriID))
}

// ReadEntriesFromContentGroupedByPath mocks base method.
func (m *MockSecretReader) ReadEntriesFromContentGroupedByPath() (secretsdb.SecretsDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEntriesFromContentGroupedByPath")
	ret0, _ := ret[0].(secretsdb.SecretsDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEntriesFromContentGroupedByPath indicates an expected call of ReadEntriesFromContentGroupedByPath.
func (mr *MockSecretReaderMockRecorder) ReadEntriesFromContentGroupedByPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEntriesFromContentGroupedByPath", reflect.TypeOf((*MockSecretReader)(nil).ReadEntriesFromContentGroupedByPath))
}
